### ISSUE TITLE
Gesture floats get changed to ints

### ISSUE THREAD

**Issue by WayaShinzui** [NotAKidOnSteam/SimpleAAS#9]
The combined animator sets the GestureLeft and GestureRight parameters to be Integers instead of Floats. Not sure if this is a bug or if it's on purpose but it's breaking the blend tree for the fist close gesture.

**Comment by NotAKidoS** [comment]
It is likely dependent on order you merge the controllers. Go one by one top-down and double check they are all floats. You may have the first controller defining the parameters as ints.

**Comment by WayaShinzui** [comment]
Omg I feel like a dingus. One of the others has the same exact
parameters but as ints. Apologies! And thank you!
